version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: desafio-picpay-postgres
    environment:
      POSTGRES_DB: desafio-picpay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - desafio-picpay-network

  redis:
    image: redis:6.2
    container_name: desafio-picpay-redis
    ports:
      - '6379:6379'
    networks:
      - desafio-picpay-network

volumes:
  postgres_data:

networks:
  desafio-picpay-network:
    driver: bridge
